import Button from '@/components/common/Button'
import { inputStyle } from '@/components/common/styles'
import type { EroticSceneConfig, EroticSceneCharacter } from '@/types/story'
import { TrashIcon, PlusIcon } from '@heroicons/react/24/outline'
import {
  LOCATIONS as EROTIC_LOCATIONS, TIMES as EROTIC_TIMES, ATMOSPHERES, PUBLICITIES,
  ROLES as EROTIC_ROLES, ROLE_LABELS, BODY_STATES, KINKS_GROUPS,
  OPENINGS, POSES, RHYTHMS, CHANGES, CLIMAXES, AFTERMATHS,
  SOUND_DENSITIES, MOAN_STYLES, DEGRADE_LANGS, POVS,
} from '@/components/common/eroticSceneConstants'
import {
  WORLD_RULES, PROP_LIST, COSTUME_LIST, STRENGTH_LABELS, SENSORY_ANCHORS,
  NOVEL_NARRATIVE_STYLES, NOVEL_TIME_COMPRESSION,
  EROTIC_PACINGS, EROTIC_BODY_LANGUAGES, EROTIC_CONSENT_DYNAMICS, EROTIC_AFTERCARE,
} from '../sceneWorkshopConstants'
import { safeCSV, AutoField, CustomTagButton, CustomInput } from "./helpers";


interface EroticSectionEditorProps {
  section: number;
  eroticConfig: EroticSceneConfig;
  editTagMode: boolean;
  onUpdateConfig: (config: EroticSceneConfig) => void;
  onToggleAuto: (field: string, v: boolean) => void;
}

export function EroticSectionEditor({ section, eroticConfig, editTagMode, onUpdateConfig, onToggleAuto }: EroticSectionEditorProps) {
    switch (section) {
      case 1: return (<AutoField field="characters" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div style={{ fontSize: 10, color: '#6b5e54', marginBottom: 6, lineHeight: 1.5 }}>参与本章涩涩场景的角色。每个角色设置其定位/身体状态/备注。</div>
          {eroticConfig.characters.map((ch, i) => (
            <div key={i} style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
              <input value={ch.characterName} onChange={e => { const nc = [...eroticConfig.characters]; nc[i] = { ...nc[i], characterName: e.target.value }; onUpdateConfig({ ...eroticConfig, characters: nc }) }} style={{ ...inputStyle, flex: 2 }} placeholder='角色名' />
              <select value={ch.role} onChange={e => { const nc = [...eroticConfig.characters]; nc[i] = { ...nc[i], role: e.target.value as EroticSceneCharacter['role'] }; onUpdateConfig({ ...eroticConfig, characters: nc }) }} style={{ ...inputStyle, flex: 1 }}>{EROTIC_ROLES.map(r => <option key={r} value={r}>{ROLE_LABELS[r]}</option>)}</select>
              <select value={ch.bodyState} onChange={e => { const nc = [...eroticConfig.characters]; nc[i] = { ...nc[i], bodyState: e.target.value }; onUpdateConfig({ ...eroticConfig, characters: nc }) }} style={{ ...inputStyle, flex: 1 }}>{BODY_STATES.map(s => <option key={s} value={s}>{s}</option>)}</select>
              <input value={ch.customNote} onChange={e => { const nc = [...eroticConfig.characters]; nc[i] = { ...nc[i], customNote: e.target.value }; onUpdateConfig({ ...eroticConfig, characters: nc }) }} style={{ ...inputStyle, flex: 2 }} placeholder='备注' />
              <button onClick={() => onUpdateConfig({ ...eroticConfig, characters: eroticConfig.characters.filter((_, j) => j !== i) })} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#d4ccc4' }}><TrashIcon style={{ width: 14, height: 14 }} /></button>
            </div>
          ))}
          <Button size='sm' variant='ghost' onClick={() => onUpdateConfig({ ...eroticConfig, characters: [...eroticConfig.characters, { characterId: '', characterName: '', role: 'sub', bodyState: '正常', customNote: '' }] })} icon={<PlusIcon style={{ width: 11, height: 11 }} />}>添加角色</Button>
        </div>
          </AutoField>)
      case 2: return (<AutoField field="location" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {EROTIC_LOCATIONS.map(p => { const sel = eroticConfig.location === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, location: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customLocation || '').split(',').filter((v: string) => v && !EROTIC_LOCATIONS.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.location === v} onToggle={() => onUpdateConfig({ ...eroticConfig, location: eroticConfig.location === v ? '卧室' : v })} onRemove={() => { onUpdateConfig({ ...eroticConfig, customLocation: (eroticConfig.customLocation||'').split(',').filter((x:string)=>x!==v).join(','), location: eroticConfig.location === v ? '卧室' : eroticConfig.location }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.customLocation || '').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customLocation: eroticConfig.customLocation ? eroticConfig.customLocation+','+v : v, location: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customLocation: (eroticConfig.customLocation||'').split(',').filter((x:string)=>x!==v).join(','), location: eroticConfig.location === v ? '卧室' : eroticConfig.location }) } />
        </div>
          </AutoField>)
      case 3: return (<AutoField field="time" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {EROTIC_TIMES.map(p => { const sel = eroticConfig.time === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, time: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customTime || '').split(',').filter((v: string) => v && !EROTIC_TIMES.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.time === v} onToggle={() => onUpdateConfig({ ...eroticConfig, time: eroticConfig.time === v ? '深夜' : v })} onRemove={() => { onUpdateConfig({ ...eroticConfig, customTime: (eroticConfig.customTime||'').split(',').filter((x:string)=>x!==v).join(','), time: eroticConfig.time === v ? '深夜' : eroticConfig.time }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.customTime || '').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customTime: eroticConfig.customTime ? eroticConfig.customTime+','+v : v, time: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customTime: (eroticConfig.customTime||'').split(',').filter((x:string)=>x!==v).join(','), time: eroticConfig.time === v ? '深夜' : eroticConfig.time }) } />
        </div>
          </AutoField>)
      case 4: return (<AutoField field="atmosphere" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {ATMOSPHERES.map(p => { const sel = eroticConfig.atmosphere === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, atmosphere: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customAtmosphere || '').split(',').filter((v: string) => v && !ATMOSPHERES.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.atmosphere === v} onToggle={() => onUpdateConfig({ ...eroticConfig, atmosphere: eroticConfig.atmosphere === v ? '羞辱' : v })} onRemove={() => { onUpdateConfig({ ...eroticConfig, customAtmosphere: (eroticConfig.customAtmosphere||'').split(',').filter((x:string)=>x!==v).join(','), atmosphere: eroticConfig.atmosphere === v ? '羞辱' : eroticConfig.atmosphere }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.customAtmosphere || '').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customAtmosphere: eroticConfig.customAtmosphere ? eroticConfig.customAtmosphere+','+v : v, atmosphere: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customAtmosphere: (eroticConfig.customAtmosphere||'').split(',').filter((x:string)=>x!==v).join(','), atmosphere: eroticConfig.atmosphere === v ? '羞辱' : eroticConfig.atmosphere }) } />
        </div>
          </AutoField>)
      case 5: return (<AutoField field="publicity" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {PUBLICITIES.map(p => { const sel = eroticConfig.publicity === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, publicity: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customPublicity || '').split(',').filter((v: string) => v && !PUBLICITIES.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.publicity === v} onToggle={() => onUpdateConfig({ ...eroticConfig, publicity: eroticConfig.publicity === v ? '私密' : v })} onRemove={() => { onUpdateConfig({ ...eroticConfig, customPublicity: (eroticConfig.customPublicity||'').split(',').filter((x:string)=>x!==v).join(','), publicity: eroticConfig.publicity === v ? '私密' : eroticConfig.publicity }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.customPublicity || '').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customPublicity: eroticConfig.customPublicity ? eroticConfig.customPublicity+','+v : v, publicity: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customPublicity: (eroticConfig.customPublicity||'').split(',').filter((x:string)=>x!==v).join(','), publicity: eroticConfig.publicity === v ? '私密' : eroticConfig.publicity }) } />
        </div>
          </AutoField>)
      case 6: return (<AutoField field="selectedKinks" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>

          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {KINKS_GROUPS.flat().map(p => { const sel = (eroticConfig.selectedKinks || []).includes(p); return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, selectedKinks: sel ? (eroticConfig.selectedKinks||[]).filter((x:string)=>x!==p) : [...(eroticConfig.selectedKinks||[]), p] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.selectedKinks || []).filter((v: string) => !KINKS_GROUPS.flat().includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, selectedKinks: (eroticConfig.selectedKinks||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, selectedKinks: (eroticConfig.selectedKinks||[]).filter((x:string)=>x!==v), customKink: (eroticConfig.customKink||'').split(',').filter((x:string)=>x!==v).join(',') }) }  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.customKink || '').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customKink: eroticConfig.customKink ? eroticConfig.customKink+','+v : v, selectedKinks: [...(eroticConfig.selectedKinks||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, customKink: (eroticConfig.customKink||'').split(',').filter((x:string)=>x!==v).join(','), selectedKinks: (eroticConfig.selectedKinks||[]).filter((x:string)=>x!==v) }) } />
        </div>
          </AutoField>)
      case 7: return (<AutoField field="mainPose" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#6b5e54', marginBottom: 6, lineHeight: 1.5 }}>性爱流程中的姿势、节奏和转换方式。姿势为主体位，节奏为抽插频率，转换为体位变化频率。</div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>姿势:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{POSES.map(p => { const sel = eroticConfig.mainPose === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, mainPose: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}{(eroticConfig.customPoses||[]).filter((v:string)=>!POSES.includes(v)).map((v:string) => <CustomTagButton key={'cp'+v} label={v} selected={eroticConfig.mainPose===v} onToggle={() => onUpdateConfig({ ...eroticConfig, mainPose: eroticConfig.mainPose===v?'无偏好':v })} onRemove={() => onUpdateConfig({ ...eroticConfig, customPoses: (eroticConfig.customPoses||[]).filter((x:string)=>x!==v), mainPose: eroticConfig.mainPose===v?'无偏好':eroticConfig.mainPose })}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay values={eroticConfig.customPoses || []} onAdd={v => onUpdateConfig({ ...eroticConfig, customPoses: [...(eroticConfig.customPoses||[]), v], mainPose: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customPoses: (eroticConfig.customPoses||[]).filter((x:string)=>x!==v), mainPose: eroticConfig.mainPose===v?'无偏好':eroticConfig.mainPose })} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>节奏:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{RHYTHMS.map(r => { const sel = eroticConfig.mainRhythm === r; return <button key={r} onClick={() => onUpdateConfig({ ...eroticConfig, mainRhythm: r })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{r}</button> })}{(eroticConfig.customRhythms||[]).filter((v:string)=>!RHYTHMS.includes(v)).map((v:string) => <CustomTagButton key={'cr'+v} label={v} selected={eroticConfig.mainRhythm===v} onToggle={() => onUpdateConfig({ ...eroticConfig, mainRhythm: eroticConfig.mainRhythm===v?'无偏好':v })} onRemove={() => onUpdateConfig({ ...eroticConfig, customRhythms: (eroticConfig.customRhythms||[]).filter((x:string)=>x!==v), mainRhythm: eroticConfig.mainRhythm===v?'无偏好':eroticConfig.mainRhythm })}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义节奏' values={eroticConfig.customRhythms || []} onAdd={v => onUpdateConfig({ ...eroticConfig, customRhythms: [...(eroticConfig.customRhythms||[]), v], mainRhythm: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customRhythms: (eroticConfig.customRhythms||[]).filter((x:string)=>x!==v), mainRhythm: eroticConfig.mainRhythm===v?'无偏好':eroticConfig.mainRhythm })} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>转换:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{CHANGES.map(ch => { const sel = eroticConfig.poseChanges === ch; return <button key={ch} onClick={() => onUpdateConfig({ ...eroticConfig, poseChanges: ch })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{ch}</button> })}{(eroticConfig.customPoseChanges||'').split(',').filter((v:string)=>v&&!CHANGES.includes(v)).map((v:string)=><CustomTagButton key={'pch'+v} label={v} selected={eroticConfig.poseChanges===v} onToggle={()=>onUpdateConfig({...eroticConfig,poseChanges:eroticConfig.poseChanges===v?'2-3次转换':v})} onRemove={()=>onUpdateConfig({...eroticConfig,customPoseChanges:(eroticConfig.customPoseChanges||'').split(',').filter((x:string)=>x!==v).join(','),poseChanges:eroticConfig.poseChanges===v?'2-3次转换':eroticConfig.poseChanges})}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义转换' values={(eroticConfig.customPoseChanges||'').split(',').filter(Boolean)} onAdd={v=>onUpdateConfig({...eroticConfig,customPoseChanges:eroticConfig.customPoseChanges?eroticConfig.customPoseChanges+','+v:v,poseChanges:v})} onRemove={v=>onUpdateConfig({...eroticConfig,customPoseChanges:(eroticConfig.customPoseChanges||'').split(',').filter((x:string)=>x!==v).join(','),poseChanges:eroticConfig.poseChanges===v?'2-3次转换':eroticConfig.poseChanges})} />
        </div>
          </AutoField>)
      case 8: return (<AutoField field="opening" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#6b5e54', marginBottom: 6, lineHeight: 1.5 }}>完整的性爱流程: 起始→主戏→高潮→余韵。AI将按此顺序组织涩涩描写。</div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>起始:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{OPENINGS.map(o => { const sel = (eroticConfig.opening||[]).includes(o); return <button key={o} onClick={() => onUpdateConfig({ ...eroticConfig, opening: sel ? eroticConfig.opening.filter((x:string)=>x!==o) : [...(eroticConfig.opening||[]), o] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{o}</button> })}{(eroticConfig.opening||[]).filter((v:string)=>!OPENINGS.includes(v)).map((v:string) => <CustomTagButton key={'op'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, opening: (eroticConfig.opening||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, opening: (eroticConfig.opening||[]).filter((x:string)=>x!==v), customOpening: (eroticConfig.customOpening||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义起始' values={eroticConfig.customOpening || []} onAdd={v => onUpdateConfig({ ...eroticConfig, customOpening: [...(eroticConfig.customOpening||[]), v], opening: [...(eroticConfig.opening||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, customOpening: (eroticConfig.customOpening||[]).filter((x:string)=>x!==v), opening: (eroticConfig.opening||[]).filter((x:string)=>x!==v) })} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>高潮:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{CLIMAXES.map(c => { const sel = (eroticConfig.climax||[]).includes(c); return <button key={c} onClick={() => onUpdateConfig({ ...eroticConfig, climax: sel ? eroticConfig.climax.filter((x:string)=>x!==c) : [...(eroticConfig.climax||[]), c] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{c}</button> })}{(eroticConfig.climax||[]).filter((v:string)=>!CLIMAXES.includes(v)).map((v:string) => <CustomTagButton key={'cl'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, climax: (eroticConfig.climax||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, climax: (eroticConfig.climax||[]).filter((x:string)=>x!==v), customClimax: (eroticConfig.customClimax||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义高潮' values={eroticConfig.customClimax || []} onAdd={v => onUpdateConfig({ ...eroticConfig, customClimax: [...(eroticConfig.customClimax||[]), v], climax: [...(eroticConfig.climax||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, customClimax: (eroticConfig.customClimax||[]).filter((x:string)=>x!==v), climax: (eroticConfig.climax||[]).filter((x:string)=>x!==v) })} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>余韵:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{AFTERMATHS.map(a => { const sel = (eroticConfig.aftermath||[]).includes(a); return <button key={a} onClick={() => onUpdateConfig({ ...eroticConfig, aftermath: sel ? (eroticConfig.aftermath||[]).filter((x:string)=>x!==a) : [...(eroticConfig.aftermath||[]), a] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{a}</button> })}{(eroticConfig.aftermath||[]).filter((v:string)=>!AFTERMATHS.includes(v)).map((v:string) => <CustomTagButton key={'af'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, aftermath: (eroticConfig.aftermath||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, aftermath: (eroticConfig.aftermath||[]).filter((x:string)=>x!==v), customAftermath: (eroticConfig.customAftermath||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义余韵' values={eroticConfig.customAftermath || []} onAdd={v => onUpdateConfig({ ...eroticConfig, customAftermath: [...(eroticConfig.customAftermath||[]), v], aftermath: [...(eroticConfig.aftermath||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, customAftermath: (eroticConfig.customAftermath||[]).filter((x:string)=>x!==v), aftermath: (eroticConfig.aftermath||[]).filter((x:string)=>x!==v) })} />
        </div>
          </AutoField>)
      case 9: return (<AutoField field="soundDensity" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>密度:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{SOUND_DENSITIES.map(s => { const sel = eroticConfig.soundDensity === s; return <button key={s} onClick={() => onUpdateConfig({ ...eroticConfig, soundDensity: s })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{s}</button> })}{(eroticConfig.customSoundDensity||'').split(',').filter((v:string)=>v&&!SOUND_DENSITIES.includes(v)).map((v:string)=><CustomTagButton key={'sd'+v} label={v} selected={eroticConfig.soundDensity===v} onToggle={()=>onUpdateConfig({...eroticConfig,soundDensity:eroticConfig.soundDensity===v?'密集':v})} onRemove={()=>onUpdateConfig({...eroticConfig,customSoundDensity:(eroticConfig.customSoundDensity||'').split(',').filter((x:string)=>x!==v).join(','),soundDensity:eroticConfig.soundDensity===v?'密集':eroticConfig.soundDensity})}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义密度' values={(eroticConfig.customSoundDensity||'').split(',').filter(Boolean)} onAdd={v=>onUpdateConfig({...eroticConfig,customSoundDensity:eroticConfig.customSoundDensity?eroticConfig.customSoundDensity+','+v:v,soundDensity:v})} onRemove={v=>onUpdateConfig({...eroticConfig,customSoundDensity:(eroticConfig.customSoundDensity||'').split(',').filter((x:string)=>x!==v).join(','),soundDensity:eroticConfig.soundDensity===v?'密集':eroticConfig.soundDensity})} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>呻吟:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{MOAN_STYLES.map(m => { const sel = eroticConfig.moanStyle === m; return <button key={m} onClick={() => onUpdateConfig({ ...eroticConfig, moanStyle: m })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{m}</button> })}{(eroticConfig.customMoanStyle||'').split(',').filter((v:string)=>v&&!MOAN_STYLES.includes(v)).map((v:string)=><CustomTagButton key={'ms'+v} label={v} selected={eroticConfig.moanStyle===v} onToggle={()=>onUpdateConfig({...eroticConfig,moanStyle:eroticConfig.moanStyle===v?'哭喊破音':v})} onRemove={()=>onUpdateConfig({...eroticConfig,customMoanStyle:(eroticConfig.customMoanStyle||'').split(',').filter((x:string)=>x!==v).join(','),moanStyle:eroticConfig.moanStyle===v?'哭喊破音':eroticConfig.moanStyle})}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义呻吟' values={(eroticConfig.customMoanStyle||'').split(',').filter(Boolean)} onAdd={v=>onUpdateConfig({...eroticConfig,customMoanStyle:eroticConfig.customMoanStyle?eroticConfig.customMoanStyle+','+v:v,moanStyle:v})} onRemove={v=>onUpdateConfig({...eroticConfig,customMoanStyle:(eroticConfig.customMoanStyle||'').split(',').filter((x:string)=>x!==v).join(','),moanStyle:eroticConfig.moanStyle===v?'哭喊破音':eroticConfig.moanStyle})} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>侮辱词:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{DEGRADE_LANGS.map(d => { const sel = (eroticConfig.degradeLangs||[]).includes(d); return <button key={d} onClick={() => onUpdateConfig({ ...eroticConfig, degradeLangs: sel ? (eroticConfig.degradeLangs||[]).filter((x:string)=>x!==d) : [...(eroticConfig.degradeLangs||[]), d] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{d}</button> })}{(eroticConfig.degradeLangs||[]).filter((v:string)=>!DEGRADE_LANGS.includes(v)).map((v:string) => <CustomTagButton key={'dl'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, degradeLangs: (eroticConfig.degradeLangs||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, degradeLangs: (eroticConfig.degradeLangs||[]).filter((x:string)=>x!==v), customDegradeLangs: (eroticConfig.customDegradeLangs||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput hideDisplay label='自定义侮辱词' values={eroticConfig.customDegradeLangs || []} onAdd={v => onUpdateConfig({ ...eroticConfig, customDegradeLangs: [...(eroticConfig.customDegradeLangs||[]), v], degradeLangs: [...(eroticConfig.degradeLangs||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, customDegradeLangs: (eroticConfig.customDegradeLangs||[]).filter((x:string)=>x!==v), degradeLangs: (eroticConfig.degradeLangs||[]).filter((x:string)=>x!==v) })} />
        </div>
          </AutoField>)
      case 10: return (<AutoField field="intensity" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            <span style={{ fontSize: 10, color: '#9b8e84', marginRight: 4 }}>强度:</span>
            {[1,2,3,4,5].map(i => { const sel = eroticConfig.intensity === i; return <button key={i} onClick={() => onUpdateConfig({ ...eroticConfig, intensity: i })} title={STRENGTH_LABELS[i]} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400, minWidth: 32, textAlign: 'center' }}>{i}</button> })}
          </div>
          <div style={{ fontSize: 10, color: '#6b5e54', marginBottom: 8, padding: '6px 10px', borderRadius: 6, background: 'rgba(0,0,0,0.02)' }}>强度说明: 1=暗示为主 2=有动作不详细 3=标准完整 4=大量细节 5=极尽细致</div>
        </div>
          </AutoField>)
      case 11: return (<AutoField field="extraNote" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#6b5e54', marginBottom: 8, padding: '6px 10px', borderRadius: 6, background: 'rgba(124,58,237,0.04)', lineHeight: 1.6 }}>这里是给 AI 的额外创作指令，会注入到模板 prompt 末尾。点击预设标签填入上方文本框。</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{(eroticConfig.customExtraNotes || '').split(',').filter(Boolean).map((v: string) => <CustomTagButton key={'ex'+v} label={v.slice(0,20)} selected={eroticConfig.extraNote === v} onToggle={() => onUpdateConfig({ ...eroticConfig, extraNote: eroticConfig.extraNote === v ? '' : v })} onRemove={() => onUpdateConfig({ ...eroticConfig, customExtraNotes: (eroticConfig.customExtraNotes||'').split(',').filter((x:string)=>x!==v).join(','), extraNote: eroticConfig.extraNote === v ? '' : eroticConfig.extraNote })}  editMode={editTagMode} />)}</div>
          <textarea value={eroticConfig.extraNote} onChange={e => onUpdateConfig({ ...eroticConfig, extraNote: e.target.value })} rows={6} style={{ ...inputStyle, width: '100%', resize: 'vertical' }} placeholder='额外说明...' />
          <CustomInput hideDisplay label='添加常用说明' values={(eroticConfig.customExtraNotes || '').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customExtraNotes: eroticConfig.customExtraNotes ? eroticConfig.customExtraNotes+','+v : v, extraNote: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customExtraNotes: (eroticConfig.customExtraNotes||'').split(',').filter((x:string)=>x!==v).join(','), extraNote: eroticConfig.extraNote === v ? '' : eroticConfig.extraNote })} />
        </div>
          </AutoField>)
      case 12: return (<AutoField field="narrativePOV" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {POVS.map(p => { const sel = eroticConfig.narrativePOV === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, narrativePOV: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {safeCSV(eroticConfig.customPOVs).split(',').filter((v: string) => v && !POVS.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.narrativePOV === v} onToggle={() => onUpdateConfig({ ...eroticConfig, narrativePOV: eroticConfig.narrativePOV === v ? '第三人称' : v })} onRemove={() => { onUpdateConfig({ ...eroticConfig, customPOVs: safeCSV(eroticConfig.customPOVs).split(',').filter((x:string)=>x!==v).join(','), narrativePOV: eroticConfig.narrativePOV === v ? '第三人称' : eroticConfig.narrativePOV }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={safeCSV(eroticConfig.customPOVs).split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customPOVs: safeCSV(eroticConfig.customPOVs) ? safeCSV(eroticConfig.customPOVs)+','+v : v, narrativePOV: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customPOVs: safeCSV(eroticConfig.customPOVs).split(',').filter((x:string)=>x!==v).join(','), narrativePOV: eroticConfig.narrativePOV === v ? '第三人称' : eroticConfig.narrativePOV }) } />
        </div>
          </AutoField>)
      case 13: return (<AutoField field="bodyFluidFocus" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>体液优先级:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{['精液','爱液','汗液','乳汁','尿液','血液'].map(f => { const sel = (eroticConfig.bodyFluidFocus||[]).includes(f); return <button key={f} onClick={() => onUpdateConfig({ ...eroticConfig, bodyFluidFocus: sel ? (eroticConfig.bodyFluidFocus||[]).filter((x:string)=>x!==f) : [...(eroticConfig.bodyFluidFocus||[]), f] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{f}</button> })}{(eroticConfig.bodyFluidFocus||[]).filter((v:string)=>!['精液','爱液','汗液','乳汁','尿液','血液'].includes(v)).map((v:string) => <CustomTagButton key={'bf'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, bodyFluidFocus: (eroticConfig.bodyFluidFocus||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, bodyFluidFocus: (eroticConfig.bodyFluidFocus||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput values={[]} onAdd={v => onUpdateConfig({ ...eroticConfig, bodyFluidFocus: [...(eroticConfig.bodyFluidFocus||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, bodyFluidFocus: (eroticConfig.bodyFluidFocus||[]).filter((x:string)=>x!==v) })} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>身体焦点:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{['胸','腿','脚','臀','腰','颈','手','眼','唇','发'].map(p => { const sel = (eroticConfig.bodyPartFocus||[]).includes(p); return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, bodyPartFocus: sel ? (eroticConfig.bodyPartFocus||[]).filter((x:string)=>x!==p) : [...(eroticConfig.bodyPartFocus||[]), p] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{p}</button> })}{(eroticConfig.bodyPartFocus||[]).filter((v:string)=>!['胸','腿','脚','臀','腰','颈','手','眼','唇','发'].includes(v)).map((v:string) => <CustomTagButton key={'bp'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, bodyPartFocus: (eroticConfig.bodyPartFocus||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, bodyPartFocus: (eroticConfig.bodyPartFocus||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput values={[]} onAdd={v => onUpdateConfig({ ...eroticConfig, bodyPartFocus: [...(eroticConfig.bodyPartFocus||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, bodyPartFocus: (eroticConfig.bodyPartFocus||[]).filter((x:string)=>x!==v) })} />
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4, marginTop: 10 }}>触感优先:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{['温度','湿度','压力','摩擦','振动'].map(t => { const sel = (eroticConfig.tactileFocus||[]).includes(t); return <button key={t} onClick={() => onUpdateConfig({ ...eroticConfig, tactileFocus: sel ? (eroticConfig.tactileFocus||[]).filter((x:string)=>x!==t) : [...(eroticConfig.tactileFocus||[]), t] })} style={{ padding: '3px 8px', borderRadius: 6, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54' }}>{t}</button> })}{(eroticConfig.tactileFocus||[]).filter((v:string)=>!['温度','湿度','压力','摩擦','振动'].includes(v)).map((v:string) => <CustomTagButton key={'tf'+v} label={v} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, tactileFocus: (eroticConfig.tactileFocus||[]).filter((x:string)=>x!==v) })} onRemove={() => onUpdateConfig({ ...eroticConfig, tactileFocus: (eroticConfig.tactileFocus||[]).filter((x:string)=>x!==v) })}  editMode={editTagMode} />)}</div>
          <CustomInput values={[]} onAdd={v => onUpdateConfig({ ...eroticConfig, tactileFocus: [...(eroticConfig.tactileFocus||[]), v] })} onRemove={v => onUpdateConfig({ ...eroticConfig, tactileFocus: (eroticConfig.tactileFocus||[]).filter((x:string)=>x!==v) })} />
        </div>
          </AutoField>)
      case 14: return (<AutoField field="narrativeStyle" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {NOVEL_NARRATIVE_STYLES.map(p => { const sel = eroticConfig.narrativeStyle === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, narrativeStyle: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.narrativeStyle || '').split(',').filter((v: string) => v && !NOVEL_NARRATIVE_STYLES.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.narrativeStyle === v} onToggle={() => onUpdateConfig({ ...eroticConfig, narrativeStyle: eroticConfig.narrativeStyle === v ? '沉浸式长镜' : v })} onRemove={() => { const filtered = (eroticConfig.narrativeStyle||'').split(',').filter((x:string)=>x!==v).join(','); onUpdateConfig({ ...eroticConfig, narrativeStyle: filtered || '沉浸式长镜' }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.narrativeStyle || '').split(',').filter((v:string)=>v&&!NOVEL_NARRATIVE_STYLES.includes(v))} onAdd={v => onUpdateConfig({ ...eroticConfig, narrativeStyle: eroticConfig.narrativeStyle ? eroticConfig.narrativeStyle+','+v : v })} onRemove={v => { const filtered = (eroticConfig.narrativeStyle||'').split(',').filter((x:string)=>x!==v).join(','); onUpdateConfig({ ...eroticConfig, narrativeStyle: filtered || '沉浸式长镜' }) }} />
        </div>
          </AutoField>)
      case 15: return (<AutoField field="timeCompression" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {NOVEL_TIME_COMPRESSION.map(p => { const sel = eroticConfig.timeCompression === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, timeCompression: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.timeCompression || '').split(',').filter((v: string) => v && !NOVEL_TIME_COMPRESSION.includes(v)).map((v: string) => <CustomTagButton key={'c'+v} label={v} selected={eroticConfig.timeCompression === v} onToggle={() => onUpdateConfig({ ...eroticConfig, timeCompression: eroticConfig.timeCompression === v ? '实时' : v })} onRemove={() => { const filtered = (eroticConfig.timeCompression||'').split(',').filter((x:string)=>x!==v).join(','); onUpdateConfig({ ...eroticConfig, timeCompression: filtered || '实时' }) }}  editMode={editTagMode} />)}
          </div>
          <CustomInput hideDisplay values={(eroticConfig.timeCompression || '').split(',').filter((v:string)=>v&&!NOVEL_TIME_COMPRESSION.includes(v))} onAdd={v => onUpdateConfig({ ...eroticConfig, timeCompression: eroticConfig.timeCompression ? eroticConfig.timeCompression+','+v : v })} onRemove={v => { const filtered = (eroticConfig.timeCompression||'').split(',').filter((x:string)=>x!==v).join(','); onUpdateConfig({ ...eroticConfig, timeCompression: filtered || '实时' }) }} />
        </div>
          </AutoField>)
      case 16: return (<AutoField field="introspection" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>内省 <span style={{ fontWeight: 400 }}>(心理描写深度)</span>:</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {[['无','不写心理描写'],['低','偶尔一笔带过角色想法'],['中','适度穿插心理活动'],['高','大量内心独白和心理分析']].map(([i,desc]) => { const sel = eroticConfig.introspection === i; return (
              <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2 }}>
                <button onClick={() => onUpdateConfig({ ...eroticConfig, introspection: i })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{i}</button>
                <span style={{ fontSize: 9, color: '#b0a69e', textAlign: 'center', maxWidth: 80 }}>{desc}</span>
              </div>
            ) })}
          </div>
        </div>
          </AutoField>)
      case 17: return (<AutoField field="sensoryAnchors" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>{SENSORY_ANCHORS.map(a => { const sel = eroticConfig.sensoryAnchors === a; return <button key={a} onClick={() => onUpdateConfig({ ...eroticConfig, sensoryAnchors: a })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{a}</button> })}{eroticConfig.sensoryAnchors && !SENSORY_ANCHORS.includes(eroticConfig.sensoryAnchors) ? <CustomTagButton key={'sa'+eroticConfig.sensoryAnchors} label={eroticConfig.sensoryAnchors} selected={true} onToggle={() => onUpdateConfig({ ...eroticConfig, sensoryAnchors: '' })} onRemove={() => onUpdateConfig({ ...eroticConfig, sensoryAnchors: '' })} editMode={editTagMode} /> : null}</div>
          <CustomInput hideDisplay values={eroticConfig.sensoryAnchors && !SENSORY_ANCHORS.includes(eroticConfig.sensoryAnchors) ? [eroticConfig.sensoryAnchors] : []} onAdd={v => onUpdateConfig({ ...eroticConfig, sensoryAnchors: v })} onRemove={() => onUpdateConfig({ ...eroticConfig, sensoryAnchors: '' })} />
        </div>
          </AutoField>)
      case 18: return (<AutoField field="dominantEmotion" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: '#6b5e54', marginBottom: 6 }}>主导情绪</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{['羞辱','快感','恐惧','温柔','支配','臣服','渴求','羞耻','爱慕','仇恨'].map(e => { const sel = eroticConfig.dominantEmotion === e; return <button key={e} onClick={() => onUpdateConfig({ ...eroticConfig, dominantEmotion: e })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{e}</button> })}</div>
            <CustomInput hideDisplay label='添加自定义情绪' values={(eroticConfig.customEmotions||'').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customEmotions: eroticConfig.customEmotions ? eroticConfig.customEmotions+','+v : v, dominantEmotion: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customEmotions: (eroticConfig.customEmotions||'').split(',').filter((x:string)=>x!==v).join(','), dominantEmotion: eroticConfig.dominantEmotion===v?'':eroticConfig.dominantEmotion })} />
            {(eroticConfig.customEmotions||'').split(',').filter(Boolean).map((v:string) => <CustomTagButton key={'em'+v} label={v} selected={eroticConfig.dominantEmotion===v} onToggle={() => onUpdateConfig({ ...eroticConfig, dominantEmotion: eroticConfig.dominantEmotion===v?'':v })} onRemove={() => onUpdateConfig({ ...eroticConfig, customEmotions: (eroticConfig.customEmotions||'').split(',').filter((x:string)=>x!==v).join(','), dominantEmotion: eroticConfig.dominantEmotion===v?'':eroticConfig.dominantEmotion })}  editMode={editTagMode} />)}
          </div>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: '#6b5e54', marginBottom: 6 }}>情绪曲线</div>
            <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>示例: 羞耻(开头)→兴奋(渐进)→失控(高潮)→羞耻(余韵)</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{(eroticConfig.customCurves||'').split(',').filter(Boolean).map((v:string) => <CustomTagButton key={'cv'+v} label={v.slice(0,25)} selected={eroticConfig.emotionCurveInput===v} onToggle={() => onUpdateConfig({ ...eroticConfig, emotionCurveInput: eroticConfig.emotionCurveInput===v?'':v })} onRemove={() => onUpdateConfig({ ...eroticConfig, customCurves: (eroticConfig.customCurves||'').split(',').filter((x:string)=>x!==v).join(','), emotionCurveInput: eroticConfig.emotionCurveInput===v?'':eroticConfig.emotionCurveInput })}  editMode={editTagMode} />)}</div>
            <input value={eroticConfig.emotionCurveInput} onChange={e => onUpdateConfig({ ...eroticConfig, emotionCurveInput: e.target.value })} style={{ ...inputStyle, width: '100%' }} placeholder='情绪(阶段)→情绪(阶段)→...' />
            <CustomInput hideDisplay label='保存曲线为预设' values={(eroticConfig.customCurves||'').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customCurves: eroticConfig.customCurves ? eroticConfig.customCurves+','+v : v, emotionCurveInput: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customCurves: (eroticConfig.customCurves||'').split(',').filter((x:string)=>x!==v).join(','), emotionCurveInput: eroticConfig.emotionCurveInput===v?'':eroticConfig.emotionCurveInput })} />
          </div>
          <div>
            <div style={{ fontSize: 11, fontWeight: 600, color: '#6b5e54', marginBottom: 6 }}>触发词</div>
            <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>角色听到/说出此词时情绪失控或转变</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>{(eroticConfig.customTriggers||'').split(',').filter(Boolean).map((v:string) => <CustomTagButton key={'tg'+v} label={v.slice(0,20)} selected={eroticConfig.triggerWords===v} onToggle={() => onUpdateConfig({ ...eroticConfig, triggerWords: eroticConfig.triggerWords===v?'':v })} onRemove={() => onUpdateConfig({ ...eroticConfig, customTriggers: (eroticConfig.customTriggers||'').split(',').filter((x:string)=>x!==v).join(','), triggerWords: eroticConfig.triggerWords===v?'':eroticConfig.triggerWords })}  editMode={editTagMode} />)}</div>
            <input value={eroticConfig.triggerWords} onChange={e => onUpdateConfig({ ...eroticConfig, triggerWords: e.target.value })} style={{ ...inputStyle, width: '100%' }} placeholder='如"求你了主人"' />
            <CustomInput hideDisplay label='保存触发词为预设' values={(eroticConfig.customTriggers||'').split(',').filter(Boolean)} onAdd={v => onUpdateConfig({ ...eroticConfig, customTriggers: eroticConfig.customTriggers ? eroticConfig.customTriggers+','+v : v, triggerWords: v })} onRemove={v => onUpdateConfig({ ...eroticConfig, customTriggers: (eroticConfig.customTriggers||'').split(',').filter((x:string)=>x!==v).join(','), triggerWords: eroticConfig.triggerWords===v?'':eroticConfig.triggerWords })} />
          </div>
        </div>
          </AutoField>)
      case 19: return (<AutoField field="worldRules" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>世界规则 — 本章特殊的设定/规则</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {WORLD_RULES.map(p => { const items = (eroticConfig.worldRules||'').split(',').map((s:string)=>s.trim()).filter(Boolean); const sel = items.includes(p); return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, worldRules: sel ? items.filter((x:string)=>x!==p).join(',') : [...items, p].join(',') })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customWorldRules||'').split(',').filter((v:string) => v && !WORLD_RULES.includes(v)).map((v:string) => { const items = (eroticConfig.worldRules||'').split(',').map((s:string)=>s.trim()).filter(Boolean); const sel = items.includes(v); return <CustomTagButton key={'c'+v} label={v} selected={sel} onToggle={() => onUpdateConfig({ ...eroticConfig, worldRules: sel ? items.filter((x:string)=>x!==v).join(',') : [...items, v].join(',') })} onRemove={() => onUpdateConfig({ ...eroticConfig, customWorldRules: (eroticConfig.customWorldRules||'').split(',').filter((x:string)=>x!==v).join(','), worldRules: items.filter((x:string)=>x!==v).join(',') })}  editMode={editTagMode} /> })}
          </div>
          <CustomInput hideDisplay label='添加自定义' values={(eroticConfig.customWorldRules||'').split(',').filter(Boolean)} onAdd={v => { const items = (eroticConfig.worldRules||'').split(',').map((s:string)=>s.trim()).filter(Boolean); onUpdateConfig({ ...eroticConfig, customWorldRules: eroticConfig.customWorldRules ? eroticConfig.customWorldRules+','+v : v, worldRules: [...items, v].join(',') }) }} onRemove={v => { const items = (eroticConfig.worldRules||'').split(',').map((s:string)=>s.trim()).filter(Boolean); onUpdateConfig({ ...eroticConfig, customWorldRules: (eroticConfig.customWorldRules||'').split(',').filter((x:string)=>x!==v).join(','), worldRules: items.filter((x:string)=>x!==v).join(',') }) }} />
        </div>
          </AutoField>)
      case 20: return (<AutoField field="propList" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>道具清单 — 本章场景中出现的道具组合</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {PROP_LIST.map(p => { const items = (eroticConfig.propList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); const sel = items.includes(p); return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, propList: sel ? items.filter((x:string)=>x!==p).join(',') : [...items, p].join(',') })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customPropLists||'').split(',').filter((v:string) => v && !PROP_LIST.includes(v)).map((v:string) => { const items = (eroticConfig.propList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); const sel = items.includes(v); return <CustomTagButton key={'c'+v} label={v} selected={sel} onToggle={() => onUpdateConfig({ ...eroticConfig, propList: sel ? items.filter((x:string)=>x!==v).join(',') : [...items, v].join(',') })} onRemove={() => onUpdateConfig({ ...eroticConfig, customPropLists: (eroticConfig.customPropLists||'').split(',').filter((x:string)=>x!==v).join(','), propList: items.filter((x:string)=>x!==v).join(',') })}  editMode={editTagMode} /> })}
          </div>
          <CustomInput hideDisplay label='添加自定义' values={(eroticConfig.customPropLists||'').split(',').filter(Boolean)} onAdd={v => { const items = (eroticConfig.propList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); onUpdateConfig({ ...eroticConfig, customPropLists: eroticConfig.customPropLists ? eroticConfig.customPropLists+','+v : v, propList: [...items, v].join(',') }) }} onRemove={v => { const items = (eroticConfig.propList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); onUpdateConfig({ ...eroticConfig, customPropLists: (eroticConfig.customPropLists||'').split(',').filter((x:string)=>x!==v).join(','), propList: items.filter((x:string)=>x!==v).join(',') }) }} />
        </div>
          </AutoField>)
      case 21: return (<AutoField field="costumeList" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 4 }}>服装清单 — 本章角色穿着组合</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 8 }}>
            {COSTUME_LIST.map(p => { const items = (eroticConfig.costumeList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); const sel = items.includes(p); return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, costumeList: sel ? items.filter((x:string)=>x!==p).join(',') : [...items, p].join(',') })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}
            {(eroticConfig.customCostumeLists||'').split(',').filter((v:string) => v && !COSTUME_LIST.includes(v)).map((v:string) => { const items = (eroticConfig.costumeList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); const sel = items.includes(v); return <CustomTagButton key={'c'+v} label={v} selected={sel} onToggle={() => onUpdateConfig({ ...eroticConfig, costumeList: sel ? items.filter((x:string)=>x!==v).join(',') : [...items, v].join(',') })} onRemove={() => onUpdateConfig({ ...eroticConfig, customCostumeLists: (eroticConfig.customCostumeLists||'').split(',').filter((x:string)=>x!==v).join(','), costumeList: items.filter((x:string)=>x!==v).join(',') })}  editMode={editTagMode} /> })}
          </div>
          <CustomInput hideDisplay label='添加自定义' values={(eroticConfig.customCostumeLists||'').split(',').filter(Boolean)} onAdd={v => { const items = (eroticConfig.costumeList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); onUpdateConfig({ ...eroticConfig, customCostumeLists: eroticConfig.customCostumeLists ? eroticConfig.customCostumeLists+','+v : v, costumeList: [...items, v].join(',') }) }} onRemove={v => { const items = (eroticConfig.costumeList||'').split(',').map((s:string)=>s.trim()).filter(Boolean); onUpdateConfig({ ...eroticConfig, customCostumeLists: (eroticConfig.customCostumeLists||'').split(',').filter((x:string)=>x!==v).join(','), costumeList: items.filter((x:string)=>x!==v).join(',') }) }} />
        </div>
          </AutoField>)
      case 22: return (<AutoField field="wordTarget" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#6b5e54', marginBottom: 8, padding: '6px 10px', borderRadius: 6, background: 'rgba(124,58,237,0.04)', lineHeight: 1.6 }}>本模板覆盖的亲密/性交场景的建议字数。区别于 AI 生成弹窗的整章字数。</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><input type='number' value={eroticConfig.wordTarget} onChange={e => { const v = parseInt(e.target.value); onUpdateConfig({ ...eroticConfig, wordTarget: isNaN(v) ? 2000 : v }) }} style={{ ...inputStyle, width: 120 }} /><span style={{ fontSize: 12, color: '#6b5e54' }}>字</span></div>
        </div>
          </AutoField>)
      case 23: return (<AutoField field="pacing" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 6 }}>涩涩节奏 — 控制场景的节奏感</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{EROTIC_PACINGS.map(p => { const sel = eroticConfig.pacing === p; return <button key={p} onClick={() => onUpdateConfig({ ...eroticConfig, pacing: p })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{p}</button> })}</div>
          <CustomInput hideDisplay label='自定义节奏' values={eroticConfig.pacing && !EROTIC_PACINGS.includes(eroticConfig.pacing) ? [eroticConfig.pacing] : []} onAdd={v => onUpdateConfig({ ...eroticConfig, pacing: v })} onRemove={() => onUpdateConfig({ ...eroticConfig, pacing: '渐进升温' })} />
        </div>
          </AutoField>)
      case 24: return (<AutoField field="bodyLanguage" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 6 }}>非言语表达 — 角色的肢体语言与微表情</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{EROTIC_BODY_LANGUAGES.map(b => { const sel = eroticConfig.bodyLanguage === b; return <button key={b} onClick={() => onUpdateConfig({ ...eroticConfig, bodyLanguage: b })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{b}</button> })}</div>
          <CustomInput hideDisplay label='自定义' values={eroticConfig.bodyLanguage && !EROTIC_BODY_LANGUAGES.includes(eroticConfig.bodyLanguage) ? [eroticConfig.bodyLanguage] : []} onAdd={v => onUpdateConfig({ ...eroticConfig, bodyLanguage: v })} onRemove={() => onUpdateConfig({ ...eroticConfig, bodyLanguage: '' })} />
        </div>
          </AutoField>)
      case 25: return (<AutoField field="consentDynamic" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 6 }}>同意动态 — 角色间的同意模式</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{EROTIC_CONSENT_DYNAMICS.map(c => { const sel = eroticConfig.consentDynamic === c; return <button key={c} onClick={() => onUpdateConfig({ ...eroticConfig, consentDynamic: c })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{c}</button> })}</div>
        </div>
          </AutoField>)
      case 26: return (<AutoField field="aftercareDetail" autoFields={eroticConfig.autoFields} onToggle={onToggleAuto}>
            <div>
          <div style={{ fontSize: 10, color: '#9b8e84', marginBottom: 6 }}>事后关怀 — 场景结束后的处理方式</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{EROTIC_AFTERCARE.map(a => { const sel = eroticConfig.aftercareDetail === a; return <button key={a} onClick={() => onUpdateConfig({ ...eroticConfig, aftercareDetail: a })} style={{ padding: '4px 10px', borderRadius: 8, border: sel ? '1px solid #dc2626' : '1px solid rgba(0,0,0,0.08)', background: sel ? 'rgba(220,38,38,0.08)' : '#fff', cursor: 'pointer', fontSize: 10, color: sel ? '#dc2626' : '#6b5e54', fontWeight: sel ? 600 : 400 }}>{a}</button> })}</div>
        </div>
          </AutoField>)
      default: return <div style={{ fontSize: 12, color: '#9b8e84', padding: 20, textAlign: 'center' }}>未知区块</div>
    }
}
